"""initial schema

Revision ID: b6c69cd4a2a7
Revises: 
Create Date: 2026-02-24 14:01:08.182324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c69cd4a2a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('main_lift', 'accessory', name='exercisecategory'), nullable=False),
    sa.Column('muscle_group', sa.Enum('chest', 'back', 'legs', 'shoulders', 'arms', 'core', name='musclegroup'), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_creator_user_id'), ['creator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_id'), ['id'], unique=False)

    op.create_table('accessory_bests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('date_set', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accessory_bests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accessory_bests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessory_bests_user_id'), ['user_id'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocks_program_id'), ['program_id'], unique=False)

    op.create_table('one_rep_maxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('date_set', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('one_rep_maxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_one_rep_maxes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_rep_maxes_user_id'), ['user_id'], unique=False)

    op.create_table('training_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_days_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_days_id'), ['id'], unique=False)

    op.create_table('planned_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('intensity_type', sa.Enum('percentage', 'rpe', 'freeform', name='intensitytype'), nullable=False),
    sa.Column('intensity_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_sets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_sets_training_day_id'), ['training_day_id'], unique=False)

    op.create_table('program_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('current_block_id', sa.Integer(), nullable=True),
    sa.Column('current_day_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['current_day_id'], ['training_days.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_runs_user_id'), ['user_id'], unique=False)

    op.create_table('scheduled_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_run_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('training_day_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['program_run_id'], ['program_runs.id'], ),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_workouts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_workouts_program_run_id'), ['program_run_id'], unique=False)

    op.create_table('completed_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_workout_id', sa.Integer(), nullable=False),
    sa.Column('planned_set_id', sa.Integer(), nullable=False),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('was_modified', sa.Boolean(), nullable=False),
    sa.Column('substituted_exercise_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['planned_set_id'], ['planned_sets.id'], ),
    sa.ForeignKeyConstraint(['scheduled_workout_id'], ['scheduled_workouts.id'], ),
    sa.ForeignKeyConstraint(['substituted_exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('completed_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completed_sets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completed_sets_scheduled_workout_id'), ['scheduled_workout_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completed_sets_scheduled_workout_id'))
        batch_op.drop_index(batch_op.f('ix_completed_sets_id'))

    op.drop_table('completed_sets')
    with op.batch_alter_table('scheduled_workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_workouts_program_run_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_workouts_id'))

    op.drop_table('scheduled_workouts')
    with op.batch_alter_table('program_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_program_runs_id'))

    op.drop_table('program_runs')
    with op.batch_alter_table('planned_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_sets_training_day_id'))
        batch_op.drop_index(batch_op.f('ix_planned_sets_id'))

    op.drop_table('planned_sets')
    with op.batch_alter_table('training_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_days_id'))
        batch_op.drop_index(batch_op.f('ix_training_days_block_id'))

    op.drop_table('training_days')
    with op.batch_alter_table('one_rep_maxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_one_rep_maxes_user_id'))
        batch_op.drop_index(batch_op.f('ix_one_rep_maxes_id'))

    op.drop_table('one_rep_maxes')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_program_id'))
        batch_op.drop_index(batch_op.f('ix_blocks_id'))

    op.drop_table('blocks')
    with op.batch_alter_table('accessory_bests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accessory_bests_user_id'))
        batch_op.drop_index(batch_op.f('ix_accessory_bests_id'))

    op.drop_table('accessory_bests')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_id'))
        batch_op.drop_index(batch_op.f('ix_programs_creator_user_id'))

    op.drop_table('programs')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
